<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pegasus.Core\Pegasus.Core.csproj" />
    <ProjectReference Include="..\..\src\Pegasus.Contracts\Pegasus.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Pegasus.Infrastructure\Pegasus.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Pegasus.Web\Pegasus.Web.csproj" />
    <ProjectReference Include="..\..\src\Pegasus.Worker\Pegasus.Worker.csproj" />
  </ItemGroup>

</Project>
